max_batch_size = 700
model_path = "models/blueprint.pt"
n_rollouts = 100

[plausible_orders_cfg]
n_plausible_orders = 8
max_actions_units_ratio = 3
req_size = 2100

[rollouts]
n_threads = 56
temperture = 0.5
top_p = 0.95
average_n_rollouts = 1
max_rollout_length = 3